### ISSUE TITLE
Support new API version from mattermost/platform

### ISSUE THREAD

**Issue by maxlmo** [makmu/outlook-matters#48]
As of version 3 of mattermost the API has changed. A version check is needed to support the new API version or choose the old one, if an old client(version < 3.0) is used.

**Comment by jabis** [comment]
Damn, I just installed the v3, no wonder it's saying cannot reach /api/v1/users/login. Is the new api that much different? Kudos anyhow - makes for an interesting plugin :+1:

**Comment by makmu** [comment]
In some parts it really is quite different. What makes it more complicated is that we want to support both v1 and v3 of the REST api (because in some companies it might take a little longer to upgrade mattermost servers to version 3). 
However, as of now, I think we are almost ready to release. Some minor issues (such as documentation) are still open but should be resolved in the next days.
